VidlyStore/Controllers/TodoListController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using VidlyStore.Models;
using VidlyStore.Models.viewModels;

namespace VidlyStore.Controllers
{
    [Authorize]
    public class TodoListController : Controller
    {
        private ApplicationDbContext _context;

        public  TodoListController()
        {
            _context = new ApplicationDbContext();
        }
        // GET: TodoList
        public ActionResult Index()
        {
            var userId = System.Web.HttpContext.Current.User.Identity.GetUserId();
            
            var allTasks = new List<TaskViewModel>();
            var today = DateTime.Today;
            var tasks = _context.task.Where(t => DbFunctions.TruncateTime(t.TaskDate) == today && 
                                                 t.ApplicationUserId == userId).OrderBy(t =>t.TaskTime).ToList();
            if (tasks.Count !=0)
            {
                
                foreach (var task in tasks)
                {
                    var taskViewModel = new TaskViewModel();
                    taskViewModel = addImaages(task);
                    allTasks.Add(taskViewModel);
                }
            }

            return View(allTasks);
        }

        // GET: TodoList/Details/5
        public ActionResult Detail(int id)
        {
            var task = _context.task.SingleOrDefault(t => t.Id == id);
            if (task == null)
            {
                return HttpNotFound();
            }
            else
            {
                var taskViewModel = new TaskViewModel();
                taskViewModel = addImaages(task);
                return View(taskViewModel);
            }
           
        }

        // GET: TodoList/Create
        public ActionResult New()
        {
            return View();
        }


        public ActionResult allTasks(FormCollection collection)
        {
           
           
                return View();
            
        }

        public ActionResult TasksList()
        {
            return View();
        }
     
        

        public TaskViewModel addImaages(task task)
        {
            var taskViewModel = new TaskViewModel();
            taskViewModel.task = task;
            var images = _context.images.Where(i => i.taskId == task.Id).ToList();
            if (images.Count != 0)
            {
                foreach (var image in images)
                {
                    if (taskViewModel.images == null)
                    {
                        //It's null - create it
                        taskViewModel.images = new List<Images>();
                    }
                    taskViewModel.images.Add(image);
                }
            }

            return taskViewModel;
        }

        // generate Json object for Calender
        public JsonResult GetCalender()
        {
            var userId = System.Web.HttpContext.Current.User.Identity.GetUserId();
            var events = _context.task.Where(t => t.ApplicationUserId == userId).ToList();
            return new JsonResult { Data = events, JsonRequestBehavior = JsonRequestBehavior.AllowGet };

        }


    }
}

VidlyStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/FontAwesome/css/all.min.css" rel="stylesheet" />
    @if (IsSectionDefined("Styles"))
    {@RenderSection("Styles", required: false)}

</head>
<body>
    @Html.Partial("_NavBar")
<div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

  
    @Scripts.Render("~/bundles/lib")
    @RenderSection("scripts", required: false)
</body>
</html>

VidlyStore/Views/Shared/_NavBar.cshtml
    
<div class="navbar  navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("CornetTask", "Index", "TodoList", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Today's Tasks", "Index", "TodoList")</li>
                <li>@Html.ActionLink("All Tasks", "allTasks", "TodoList")</li>
                <li>@Html.ActionLink("New Task","New", "TodoList")</li>
            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </div>
</div>
<!------------------------------------------------------------------------------------------------->